 
 
CREATE TABLE SERVICEREQ
(
	ID INT IDENTITY(1000,1) NOT NULL PRIMARY KEY,
	REQ_OPEN_TIME DATETIME,
	REQ_DESC VARCHAR(200),
	STAT VARCHAR(10),
	REQ_CLOSED_TIME DATETIME
)
 
CREATE TRIGGER DATE_INSERT ON SERVICEREQ
AFTER INSERT
AS
BEGIN
	DECLARE @TEMPID AS INT
	SELECT @TEMPID=ID FROM inserted
	UPDATE SERVICEREQ SET REQ_OPEN_TIME=GETDATE() WHERE ID=@TEMPID
END

CREATE TRIGGER CLOSE_DATE ON SERVICEREQ
AFTER UPDATE
AS
BEGIN
	DECLARE @STAT_TEMP AS VARCHAR(10)
	SELECT @STAT_TEMP=STAT FROM SERVICEREQ
	UPDATE SERVICEREQ SET REQ_CLOSED_TIME=GETDATE() WHERE STAT='Closed'
END

SELECT * FROM SERVICEREQ
	
